services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: urban-connection
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
